sudo: required

language: python

services:
- docker

env:
- DOCKER_REPO=ivarprudnikov/rnn-generator
- REGISTRY_URL=630017267485.dkr.ecr.eu-west-1.amazonaws.com

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

script:
- docker build -t $DOCKER_REPO .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
